/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * DB-exists health gate
         * @description Report whether the configured SQLite DB is present.
         *
         *     Always HTTP 200 so the client can read the body and decide; ``status`` is
         *     ``"ok"`` only when the DB file exists, otherwise ``"degraded"``.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List persisted scenario ids
         * @description Distinct persisted scenario ids (sorted) and their count.
         */
        get: operations["list_scenarios_api_v1_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest-results/nav-comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * NAV comparison + summary
         * @description Per-scenario NAV lines, dashed B&H benchmarks, and the summary table (Tab 1).
         */
        get: operations["nav_comparison_api_v1_backtest_results_nav_comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest-results/returns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily returns scatter
         * @description Columnar daily-return series per scenario for the WebGL scatter (Tab 2).
         */
        get: operations["returns_api_v1_backtest_results_returns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/etf-prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ETF close-price lines
         * @description One close-price :class:`NamedSeries` per ticker (Tab 4 chart).
         */
        get: operations["etf_prices_api_v1_etf_prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/etf-prices/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ETF price statistics
         * @description Per-ticker first/last/min/max close + total return (Tab 4 table).
         */
        get: operations["etf_price_stats_api_v1_etf_prices_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * EtfPriceStatsResponse
         * @description The price-statistics table as a list of typed rows.
         */
        EtfPriceStatsResponse: {
            /** Stats */
            stats: components["schemas"]["PriceStat"][];
        };
        /**
         * EtfPricesResponse
         * @description Close-price lines, one :class:`NamedSeries` per ticker (Tab 4 chart).
         */
        EtfPricesResponse: {
            /** Series */
            series: components["schemas"]["NamedSeries"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description DB-exists gate -- replaces the Streamlit ``app.py`` ``DB_PATH.exists()`` check.
         *
         *     ``status`` is ``"ok"`` only when the configured SQLite DB file is present and
         *     readable. The React ``HealthGate`` blocks the app on anything else.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Db Exists */
            db_exists: boolean;
            /** Db Path */
            db_path: string;
            /** Api Version */
            api_version: string;
        };
        /**
         * NamedSeries
         * @description A named chart trace: a legend label plus its (x, y) points.
         */
        NamedSeries: {
            /** Name */
            name: string;
            /** Points */
            points: components["schemas"]["SeriesPoint"][];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * NavComparisonResponse
         * @description Tab 1: scenario NAV lines + dashed B&H benchmark lines + summary table.
         */
        NavComparisonResponse: {
            /** Start Date */
            start_date: string | null;
            /** Initial Nav */
            initial_nav: number;
            /** Scenario Series */
            scenario_series: components["schemas"]["NamedSeries"][];
            /** Benchmark Series */
            benchmark_series: components["schemas"]["NamedSeries"][];
            /** Summary */
            summary: components["schemas"]["ScenarioSummaryRow"][];
        };
        /**
         * PriceStat
         * @description Per-ticker price statistics (Tab 4 table). Floats are nullable per §6.
         *
         *     ``total_return`` is a decimal fraction (``last/first - 1``), e.g. ``0.42`` =
         *     42% -- formatting is the client's job (§4.1).
         */
        PriceStat: {
            /** Ticker */
            ticker: string;
            /** First Close */
            first_close: number | null;
            /** Last Close */
            last_close: number | null;
            /** Min Close */
            min_close: number | null;
            /** Max Close */
            max_close: number | null;
            /** Total Return */
            total_return: number | null;
        };
        /**
         * ReturnsResponse
         * @description Tab 2: one columnar return series per scenario (rendered via Plotly WebGL).
         */
        ReturnsResponse: {
            /** Series */
            series: components["schemas"]["ReturnsScatterSeries"][];
        };
        /**
         * ReturnsScatterSeries
         * @description Daily returns for one scenario, columnar (parallel ``dates``/``returns``).
         */
        ReturnsScatterSeries: {
            /** Scenario Id */
            scenario_id: string;
            /** Dates */
            dates: string[];
            /** Returns */
            returns: (number | null)[];
        };
        /**
         * ScenarioSummaryRow
         * @description One row of the "Scenario Performance Summary" table (Tab 1).
         */
        ScenarioSummaryRow: {
            /** Scenario Id */
            scenario_id: string;
            /** Final Nav */
            final_nav: number | null;
            /** Total Return */
            total_return: number | null;
            /** Max Drawdown */
            max_drawdown: number | null;
            /** Annualized Volatility */
            annualized_volatility: number | null;
        };
        /**
         * ScenariosResponse
         * @description Distinct persisted scenario ids (sorted) plus their count.
         */
        ScenariosResponse: {
            /** Scenarios */
            scenarios: string[];
            /** Count */
            count: number;
        };
        /**
         * SeriesPoint
         * @description A single (x, y) point. ``value`` is ``None`` for NaN/Inf (§6).
         */
        SeriesPoint: {
            /** Date */
            date: string;
            /** Value */
            value: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_scenarios_api_v1_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenariosResponse"];
                };
            };
        };
    };
    nav_comparison_api_v1_backtest_results_nav_comparison_get: {
        parameters: {
            query?: {
                /** @description Comma-separated scenario ids (case-sensitive). Omit for all. */
                scenario_ids?: string | null;
                /** @description Comma-separated benchmark tickers (TLT,AGG,SHY). Omit for all three. */
                benchmarks?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavComparisonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    returns_api_v1_backtest_results_returns_get: {
        parameters: {
            query?: {
                /** @description Comma-separated scenario ids (case-sensitive). Omit for all. */
                scenario_ids?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReturnsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    etf_prices_api_v1_etf_prices_get: {
        parameters: {
            query?: {
                /** @description Comma-separated tickers (e.g. TLT,AGG,SHY). Omit for all. */
                tickers?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtfPricesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    etf_price_stats_api_v1_etf_prices_stats_get: {
        parameters: {
            query?: {
                /** @description Comma-separated tickers (e.g. TLT,AGG,SHY). Omit for all. */
                tickers?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtfPriceStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
