/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * DB-exists health gate
         * @description Report whether the configured SQLite DB is present.
         *
         *     Always HTTP 200 so the client can read the body and decide; ``status`` is
         *     ``"ok"`` only when the DB file exists, otherwise ``"degraded"``.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List persisted scenario ids
         * @description Distinct persisted scenario ids (sorted) and their count.
         */
        get: operations["list_scenarios_api_v1_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest-results/nav-comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * NAV comparison + summary
         * @description Per-scenario NAV lines, dashed B&H benchmarks, and the summary table (Tab 1).
         */
        get: operations["nav_comparison_api_v1_backtest_results_nav_comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest-results/returns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily returns scatter
         * @description Columnar daily-return series per scenario for the WebGL scatter (Tab 2).
         */
        get: operations["returns_api_v1_backtest_results_returns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest-results/returns-diagnostic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns Analysis diagnostic payload
         * @description Enriched per-scenario scatter + boxplot distribution + worst/best/dispersion
         *     tables for the redesigned Returns Analysis view. Ships every scenario at once
         *     so the page toggles curve visibility client-side (no refetch).
         *
         *     Returns an ``ORJSONResponse`` directly: the service builds the (large) payload
         *     as a plain dict and we skip Pydantic response validation for speed
         *     (``response_model`` above still drives the OpenAPI schema).
         */
        get: operations["returns_diagnostic_api_v1_backtest_results_returns_diagnostic_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest-results/returns-diagnostic/point": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Single-point diagnostic detail (click drilldown)
         * @description Rich per-point context for the Returns Analysis click drilldown (one row).
         */
        get: operations["returns_diagnostic_point_api_v1_backtest_results_returns_diagnostic_point_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest-results/{scenario_id}/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily rows for a scenario
         * @description Raw daily rows for one scenario (Tab 3 table).
         */
        get: operations["daily_api_v1_backtest_results__scenario_id__daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tearsheet/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full tearsheet for a scenario
         * @description Metrics + equity/drawdown/rolling curves + exposure/regime/benchmark tables.
         */
        get: operations["tearsheet_api_v1_tearsheet__scenario_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/etf-prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ETF close-price lines
         * @description One close-price :class:`NamedSeries` per ticker (Tab 4 chart).
         */
        get: operations["etf_prices_api_v1_etf_prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/etf-prices/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ETF price statistics
         * @description Per-ticker first/last/min/max close + total return (Tab 4 table).
         */
        get: operations["etf_price_stats_api_v1_etf_prices_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/volatility-features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vol estimate lines for a ticker
         * @description Per-method annualized-vol lines for one ticker (Tab 5 chart).
         */
        get: operations["volatility_features_api_v1_volatility_features_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/volatility-features/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest vol per ticker
         * @description Latest annualized vol per method per ticker (Tab 5 table).
         */
        get: operations["volatility_latest_api_v1_volatility_features_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/volatility-features/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Surface data-contract warnings
         * @description Phase 0 data-contract diagnostics for the persisted surface (read-only).
         */
        get: operations["volatility_audit_api_v1_volatility_features_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/volatility-features/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unified chart data (series + shading + transitions)
         * @description Typed chart payload for the Phase 6 diagnostic chart (no server-built figure).
         */
        get: operations["volatility_chart_api_v1_volatility_features_chart_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/volatility-features/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest percentile context
         * @description Current vol + historical percentile + level for one ticker (Phase 1 card).
         */
        get: operations["volatility_context_api_v1_volatility_features_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/volatility-features/percentile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historical percentile line
         * @description The 0.0–1.0 historical-percentile line for the Phase 1 percentile view.
         */
        get: operations["volatility_percentile_api_v1_volatility_features_percentile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/volatility-features/state-table": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All-asset confirmed-state table
         * @description Latest confirmed diagnostic state per asset (Phase 3 all-asset table).
         */
        get: operations["volatility_state_table_api_v1_volatility_features_state_table_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/volatility-features/agreement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estimator agreement + comparison panel
         * @description Cross-estimator agreement (relative + absolute) and the per-estimator comparison panel.
         */
        get: operations["volatility_agreement_api_v1_volatility_features_agreement_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/volatility-features/derived": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Term-ratio / change / dispersion line
         * @description 20D/60D term ratio, relative volatility change, or estimator dispersion (Phase 2/4 chart views).
         */
        get: operations["volatility_derived_api_v1_volatility_features_derived_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Macro indicator series
         * @description One series per requested macro indicator (each on its own date axis).
         */
        get: operations["macro_api_v1_macro_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro/yield-curve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 10Y/2Y yields + spread
         * @description 10Y and 2Y yields plus the 10Y-2Y spread.
         */
        get: operations["yield_curve_api_v1_macro_yield_curve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest macro snapshot cards
         * @description Latest reading of each headline indicator (per-card observation dates).
         */
        get: operations["snapshot_api_v1_macro_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro/regime-timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Macro-regime timeline
         * @description Dashboard macro-regime over time + optional engine duration-support overlay.
         */
        get: operations["regime_timeline_api_v1_macro_regime_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro/conditional-returns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Forward returns by regime
         * @description Regime × ETF forward-return statistics (descriptive; see response notes).
         */
        get: operations["conditional_returns_api_v1_macro_conditional_returns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro/forward-return-scatter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Macro vs forward-return scatter
         * @description (macro reading, subsequent ETF return) points for the explorer scatter mode.
         */
        get: operations["forward_return_scatter_api_v1_macro_forward_return_scatter_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Strategy registry introspection
         * @description Flatten the ``STRATEGIES`` registry so the UI can decode scenario names.
         */
        get: operations["strategies_api_v1_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger a backtest run
         * @description Launch a backtest over the registry (or a subset); returns 202 + the job.
         */
        post: operations["trigger_backtest_api_v1_jobs_backtest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List backtest jobs
         * @description All jobs this process has seen (in-process registry).
         */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll a backtest job
         * @description Status of one job; 404 if the id is unknown to this process.
         */
        get: operations["job_status_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a running backtest
         * @description Terminate a queued/running job's subprocess; a no-op if it already finished.
         */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BacktestDailyResponse
         * @description Endpoint 4 (Tab 3 raw table): one scenario's daily rows, paginated.
         *
         *     ``table`` carries the requested columns (default: the scalar display set the
         *     Streamlit tab shows). ``total_rows`` is the unpaginated count for the scenario.
         */
        BacktestDailyResponse: {
            /** Scenario Id */
            scenario_id: string;
            /** Total Rows */
            total_rows: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number | null;
            table: components["schemas"]["TableModel"];
        };
        /**
         * BacktestJobRequest
         * @description Trigger body: an optional subset of strategy names (``None`` = whole registry).
         */
        BacktestJobRequest: {
            /** Strategy Names */
            strategy_names?: string[] | null;
        };
        /**
         * CategoricalPoint
         * @description A point in a categorical-over-time series: an ordinal ``value`` (the code,
         *     ``None`` where undefined) plus its human-readable ``label`` (spec §12 #5).
         */
        CategoricalPoint: {
            /** Date */
            date: string;
            /** Value */
            value: number | null;
            /** Label */
            label?: string | null;
        };
        /**
         * CategoricalSeries
         * @description A named categorical-over-time trace (regime ribbons, curve states).
         *
         *     Kept separate from :class:`NamedSeries` so the dense numeric series never pay
         *     for a per-point ``label`` field (spec §12 #5 intent, implemented leanly).
         *     ``categories`` maps each ordinal code (as a string) to its label.
         */
        CategoricalSeries: {
            /** Name */
            name: string;
            /** Points */
            points: components["schemas"]["CategoricalPoint"][];
            /** Categories */
            categories: {
                [key: string]: string;
            };
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ConditionalReturnsResponse
         * @description How TLT/AGG/SHY behaved *after* each macro regime (spec Phase 5).
         *
         *     A regime × ETF :class:`TableModel` of forward-return statistics. This is
         *     **descriptive, not predictive**: ``is_lagged`` records that macro is lagged to
         *     an availability proxy (no look-ahead); ``point_in_time_release_available`` is
         *     ``False`` (FRED gives reference months, not release dates); and ``notes``
         *     carries the overlapping-horizon / small-sample caveats the UI must surface.
         *     Forward returns are decimal fractions; a ``thin`` row flag marks regimes with
         *     fewer than the requested minimum observations.
         */
        ConditionalReturnsResponse: {
            table: components["schemas"]["TableModel"];
            /** Is Lagged */
            is_lagged: boolean;
            /** Point In Time Release Available */
            point_in_time_release_available: boolean;
            /** Notes */
            notes: string[];
        };
        /**
         * EstimatorAgreementResponse
         * @description Estimator-agreement summary + per-estimator comparison panel (Phase 4).
         */
        EstimatorAgreementResponse: {
            /** Ticker */
            ticker: string;
            /** Config Key */
            config_key: string;
            /** Agreement */
            agreement: string;
            /** Absolute Spread */
            absolute_spread: number | null;
            /** Relative Dispersion */
            relative_dispersion: number | null;
            /** Highest Estimator */
            highest_estimator: string | null;
            /** Lowest Estimator */
            lowest_estimator: string | null;
            /** Agreement Config Version */
            agreement_config_version: string;
            /** Rows */
            rows: components["schemas"]["EstimatorComparisonRow"][];
        };
        /**
         * EstimatorComparisonRow
         * @description One estimator's reading vs the cross-estimator median (Phase 4 panel).
         *
         *     The old ambiguous "Difference vs Median" is split into an explicit absolute
         *     (annualised-vol percentage-point) column and a relative (%) column.
         */
        EstimatorComparisonRow: {
            /** Estimator */
            estimator: string;
            /** Method */
            method: string;
            /** Current Volatility */
            current_volatility: number | null;
            /** Historical Percentile Ordinal */
            historical_percentile_ordinal: number | null;
            /** Absolute Diff Vs Median */
            absolute_diff_vs_median: number | null;
            /** Relative Diff Vs Median */
            relative_diff_vs_median: number | null;
        };
        /**
         * EtfPriceStatsResponse
         * @description The price-statistics table as a list of typed rows.
         */
        EtfPriceStatsResponse: {
            /** Stats */
            stats: components["schemas"]["PriceStat"][];
        };
        /**
         * EtfPricesResponse
         * @description Close-price lines, one :class:`NamedSeries` per ticker (Tab 4 chart).
         */
        EtfPricesResponse: {
            /** Series */
            series: components["schemas"]["NamedSeries"][];
        };
        /**
         * ForwardReturnScatterResponse
         * @description Δ-macro vs subsequent-ETF-return scatter (spec §18 explorer display mode).
         *
         *     Each point pairs a macro indicator's value at month ``date`` with the ETF's
         *     forward total return over ``horizon``, measured only *after* the reading was
         *     knowable (lagged, no look-ahead). Descriptive — association is not causation,
         *     and overlapping windows make the points non-independent (see ``note``).
         */
        ForwardReturnScatterResponse: {
            /** Points */
            points: components["schemas"]["ScatterPoint"][];
            /** Etf */
            etf: string;
            /** Horizon */
            horizon: string;
            /** X Key */
            x_key: string;
            /** X Label */
            x_label: string;
            /** X Unit */
            x_unit: string | null;
            /** N */
            n: number;
            /** Note */
            note: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description DB-exists gate -- replaces the Streamlit ``app.py`` ``DB_PATH.exists()`` check.
         *
         *     ``status`` is ``"ok"`` only when the configured SQLite DB file is present and
         *     readable. The React ``HealthGate`` blocks the app on anything else.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Db Exists */
            db_exists: boolean;
            /** Db Path */
            db_path: string;
            /** Api Version */
            api_version: string;
        };
        /**
         * JobStatus
         * @description A backtest job's state (polled via ``GET /jobs/{job_id}``).
         */
        JobStatus: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Strategy Names */
            strategy_names: string[] | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Scenario Ids Written */
            scenario_ids_written: string[] | null;
            /** Detail */
            detail: string | null;
            /** Progress Current */
            progress_current: number | null;
            /** Progress Total */
            progress_total: number | null;
            /** Progress Strategy */
            progress_strategy: string | null;
        };
        /**
         * MacroResponse
         * @description One :class:`NamedSeries` per requested indicator (name = indicator key).
         */
        MacroResponse: {
            /** Series */
            series: components["schemas"]["NamedSeries"][];
        };
        /**
         * MacroSnapshotCard
         * @description The latest reading of one indicator (spec Page 6 snapshot cards).
         *
         *     Each card carries its **own** ``observation_date`` -- a monthly series must
         *     never be shown as if it shared a daily series' date. ``value`` is a number for
         *     numeric indicators or a label string for categorical ones (e.g. the curve
         *     regime). ``change_3m`` / ``direction`` summarise 3-month momentum.
         */
        MacroSnapshotCard: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: number | string | null;
            /** Unit */
            unit: string | null;
            /** Observation Date */
            observation_date: string | null;
            /** Change 3M */
            change_3m: number | null;
            /** Direction */
            direction: string | null;
            /** Is Stale */
            is_stale: boolean;
        };
        /**
         * MacroSnapshotResponse
         * @description Latest-reading snapshot cards + the newest macro date they're measured against.
         */
        MacroSnapshotResponse: {
            /** Cards */
            cards: components["schemas"]["MacroSnapshotCard"][];
            /** As Of */
            as_of: string;
        };
        /**
         * NamedSeries
         * @description A named chart trace: a legend label plus its (x, y) points.
         */
        NamedSeries: {
            /** Name */
            name: string;
            /** Points */
            points: components["schemas"]["SeriesPoint"][];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * NavComparisonResponse
         * @description Tab 1: scenario NAV lines + dashed B&H benchmark lines + summary table.
         */
        NavComparisonResponse: {
            /** Start Date */
            start_date: string | null;
            /** Initial Nav */
            initial_nav: number;
            /** Scenario Series */
            scenario_series: components["schemas"]["NamedSeries"][];
            /** Benchmark Series */
            benchmark_series: components["schemas"]["NamedSeries"][];
            /** Summary */
            summary: components["schemas"]["ScenarioSummaryRow"][];
        };
        /**
         * PriceStat
         * @description Per-ticker price statistics (Tab 4 table). Floats are nullable per §6.
         *
         *     ``total_return`` is a decimal fraction (``last/first - 1``), e.g. ``0.42`` =
         *     42% -- formatting is the client's job (§4.1).
         */
        PriceStat: {
            /** Ticker */
            ticker: string;
            /** First Close */
            first_close: number | null;
            /** Last Close */
            last_close: number | null;
            /** Min Close */
            min_close: number | null;
            /** Max Close */
            max_close: number | null;
            /** Total Return */
            total_return: number | null;
        };
        /**
         * RegimeTimelineResponse
         * @description Macro-regime timeline for shading an ETF chart (spec Phase 4).
         *
         *     ``regime`` is the dashboard's transparent rule-based classification over time
         *     (categorical). ``engine_regime`` is an optional comparison overlay from the
         *     engine's persisted ``macro_supports_duration`` signal (decision #6: surface
         *     both; ``None`` if no backtest regime trace exists). ``legend`` maps each
         *     dashboard regime to its economic-prior bond preference (a prior, not a fitted
         *     result). The dashboard regimes are explanatory and must NOT be read as the
         *     engine's allocation regimes.
         */
        RegimeTimelineResponse: {
            regime: components["schemas"]["CategoricalSeries"];
            engine_regime: components["schemas"]["CategoricalSeries"] | null;
            /** Legend */
            legend: {
                [key: string]: string;
            };
        };
        /**
         * ReturnsDiagnosticResponse
         * @description The full Returns Analysis diagnostic payload (scatter + boxplot + tables).
         *
         *     The entire scenario universe is shipped at once (``series`` / ``distribution``
         *     cover every scenario), so the page toggles curve visibility client-side via
         *     the Plotly legend with no further fetches. ``default_visible`` names the few
         *     scenarios drawn visible on first load; the rest start ``legendonly``.
         */
        ReturnsDiagnosticResponse: {
            /** Available Scenarios */
            available_scenarios: components["schemas"]["ScenarioMeta"][];
            /** Default Visible */
            default_visible: string[];
            /** Date Min */
            date_min: string | null;
            /** Date Max */
            date_max: string | null;
            /** Filter Mode */
            filter_mode: string;
            /** Series */
            series: components["schemas"]["ReturnsDiagnosticSeries"][];
            /** Distribution */
            distribution: components["schemas"]["ReturnsDistributionSeries"][];
            worst: components["schemas"]["TableModel"];
            best: components["schemas"]["TableModel"];
            dispersion: components["schemas"]["TableModel"];
        };
        /**
         * ReturnsDiagnosticSeries
         * @description One scenario's scatter points (date-range + return-filter scoped).
         *
         *     Columnar (parallel arrays) to avoid per-point object allocation, mirroring
         *     ``ReturnsScatterSeries``. Intentionally lean -- date + return only -- so the
         *     full grid ships cheaply and legend toggles never refetch. Rich per-point
         *     context lives in the diagnostic tables and the on-demand click drilldown
         *     (``ReturnsPointDetail``), not in this array.
         */
        ReturnsDiagnosticSeries: {
            /** Scenario Id */
            scenario_id: string;
            /** Scenario Label */
            scenario_label: string;
            /** Dates */
            dates: string[];
            /** Returns */
            returns: (number | null)[];
        };
        /**
         * ReturnsDistributionSeries
         * @description One scenario's full date-range return distribution (for the boxplot).
         *
         *     Not restricted by the chart's return-filter mode -- a boxplot of only the
         *     outliers would be meaningless, so this always spans the selected date range.
         */
        ReturnsDistributionSeries: {
            /** Scenario Id */
            scenario_id: string;
            /** Scenario Label */
            scenario_label: string;
            /** Returns */
            returns: (number | null)[];
        };
        /**
         * ReturnsPointDetail
         * @description Rich diagnostic detail for a single (scenario, date) -- the click drilldown.
         *
         *     Fetched on demand (one row) so the main scatter payload stays lean. ``lines``
         *     are the pre-formatted, missing-field-omitted diagnostic lines the panel renders.
         */
        ReturnsPointDetail: {
            /** Scenario Id */
            scenario_id: string;
            /** Scenario Label */
            scenario_label: string;
            /** Date */
            date: string | null;
            /** Daily Return */
            daily_return: number | null;
            /** Lines */
            lines: string[];
        };
        /**
         * ReturnsResponse
         * @description Tab 2: one columnar return series per scenario (rendered via Plotly WebGL).
         */
        ReturnsResponse: {
            /** Series */
            series: components["schemas"]["ReturnsScatterSeries"][];
        };
        /**
         * ReturnsScatterSeries
         * @description Daily returns for one scenario, columnar (parallel ``dates``/``returns``).
         */
        ReturnsScatterSeries: {
            /** Scenario Id */
            scenario_id: string;
            /** Dates */
            dates: string[];
            /** Returns */
            returns: (number | null)[];
        };
        /**
         * ScatterPoint
         * @description One month: a macro reading (``x``) vs the ETF's subsequent return (``y``).
         */
        ScatterPoint: {
            /** Date */
            date: string;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * ScenarioMeta
         * @description A scenario's readable label + parsed metadata, for the UI filters/picker.
         *
         *     Shipped for *every* available scenario (not just the selected ones) so the
         *     family / volatility-method / target-vol filters and the multi-select can be
         *     populated without a second round-trip. Metadata fields are nullable: an
         *     unparseable id degrades gracefully rather than failing.
         */
        ScenarioMeta: {
            /** Scenario Id */
            scenario_id: string;
            /** Scenario Label */
            scenario_label: string;
            /** Family */
            family: string | null;
            /** Lookback */
            lookback: number | null;
            /** Vol Method */
            vol_method: string | null;
            /** Cov Lookback */
            cov_lookback: number | null;
            /** Ewma Lambda */
            ewma_lambda: number | null;
            /** Target Vol */
            target_vol: number | null;
        };
        /**
         * ScenarioSummaryRow
         * @description One row of the "Scenario Performance Summary" table (Tab 1).
         */
        ScenarioSummaryRow: {
            /** Scenario Id */
            scenario_id: string;
            /** Final Nav */
            final_nav: number | null;
            /** Total Return */
            total_return: number | null;
            /** Max Drawdown */
            max_drawdown: number | null;
            /** Annualized Volatility */
            annualized_volatility: number | null;
        };
        /**
         * ScenariosResponse
         * @description Distinct persisted scenario ids (sorted) plus their count.
         */
        ScenariosResponse: {
            /** Scenarios */
            scenarios: string[];
            /** Count */
            count: number;
        };
        /**
         * SeriesPoint
         * @description A single (x, y) point. ``value`` is ``None`` for NaN/Inf (§6).
         */
        SeriesPoint: {
            /** Date */
            date: string;
            /** Value */
            value: number | null;
        };
        /**
         * StrategiesResponse
         * @description The whole registry plus the currently-selected live strategy name.
         */
        StrategiesResponse: {
            /** Live Strategy */
            live_strategy: string;
            /** Strategies */
            strategies: components["schemas"]["StrategySummary"][];
        };
        /**
         * StrategySummary
         * @description A flattened view of one ``StrategyConfig`` (selected knobs from its sub-configs).
         */
        StrategySummary: {
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Starting Weight Source */
            starting_weight_source: string;
            /** Use Vol Scaling */
            use_vol_scaling: boolean;
            /** Vol Scaling Power */
            vol_scaling_power: number;
            /** Use Covariance Scaling */
            use_covariance_scaling: boolean;
            /** Target Portfolio Vol */
            target_portfolio_vol: number;
            /** Cov Method */
            cov_method: string;
            /** Is Live */
            is_live: boolean;
        };
        /**
         * TableModel
         * @description A generic table: column order plus list-of-records rows (values JSON scalars or null).
         */
        TableModel: {
            /** Columns */
            columns: string[];
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
        };
        /**
         * TearsheetMetricsModel
         * @description Flat view of ``TearsheetMetrics`` (all 26 fields).
         */
        TearsheetMetricsModel: {
            /** Scenario Id */
            scenario_id: string;
            /** Start Date */
            start_date: string;
            /** End Date */
            end_date: string;
            /** Total Return */
            total_return: number | null;
            /** Cagr */
            cagr: number | null;
            /** Annualized Volatility */
            annualized_volatility: number | null;
            /** Sharpe */
            sharpe: number | null;
            /** Sortino */
            sortino: number | null;
            /** Max Drawdown */
            max_drawdown: number | null;
            /** Calmar */
            calmar: number | null;
            /** Var 95 */
            var_95: number | null;
            /** Cvar 95 */
            cvar_95: number | null;
            /** Worst Day */
            worst_day: number | null;
            /** Best Day */
            best_day: number | null;
            /** Skew */
            skew: number | null;
            /** Excess Kurtosis */
            excess_kurtosis: number | null;
            /** Avg Turnover */
            avg_turnover: number | null;
            /** Annualized Turnover */
            annualized_turnover: number | null;
            /** Total Cost */
            total_cost: number | null;
            /** Cost Drag */
            cost_drag: number | null;
            /** Daily Hit Rate */
            daily_hit_rate: number | null;
            /** Avg Win */
            avg_win: number | null;
            /** Avg Loss */
            avg_loss: number | null;
            /** Payoff Ratio */
            payoff_ratio: number | null;
            /** Profit Factor */
            profit_factor: number | null;
            /** Parametric Var 95 */
            parametric_var_95: number | null;
        };
        /**
         * TearsheetResponse
         * @description Full tearsheet: metrics + equity/drawdown/rolling curves + summary tables.
         */
        TearsheetResponse: {
            summary: components["schemas"]["TearsheetMetricsModel"];
            equity_curve: components["schemas"]["NamedSeries"];
            drawdown_curve: components["schemas"]["NamedSeries"];
            /** Rolling Metrics */
            rolling_metrics: components["schemas"]["NamedSeries"][];
            exposure_summary: components["schemas"]["TableModel"] | null;
            regime_summary: components["schemas"]["TableModel"] | null;
            benchmark_summary: components["schemas"]["TableModel"] | null;
            /** Regime Match Rate */
            regime_match_rate: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VolLatestRow
         * @description Latest annualized vol per method for one ticker (Tab 5 table).
         */
        VolLatestRow: {
            /** Ticker */
            ticker: string;
            /** Date */
            date: string | null;
            /** Rolling 20 */
            rolling_20: number | null;
            /** Rolling 60 */
            rolling_60: number | null;
            /** Ewma 94 */
            ewma_94: number | null;
            /** Ewma 97 */
            ewma_97: number | null;
            /** Garch */
            garch: number | null;
        };
        /**
         * VolatilityAuditResponse
         * @description Phase 0 data-contract diagnostics for the persisted surface.
         *
         *     ``warnings`` is the (possibly empty) list of non-fatal data-quality findings
         *     from ``validate_volatility_surface``; an empty list means the surface passed
         *     every check. ``config_keys`` and ``n_rows`` describe the audited slice. This
         *     is a read-only diagnostic endpoint and must never break the page.
         */
        VolatilityAuditResponse: {
            /** Warnings */
            warnings: string[];
            /** Config Keys */
            config_keys: string[];
            /** N Rows */
            n_rows: number;
        };
        /**
         * VolatilityChartResponse
         * @description Unified typed chart payload for any view (Phase 6).
         *
         *     React assembles the Plotly traces from ``series``; ``state_ranges`` drive
         *     optional shading, ``transitions`` drive optional markers, ``reference_lines``
         *     are horizontal guides, and ``unit`` is the axis unit for ``view_mode``. No
         *     ``go.Figure`` is ever built on the backend.
         */
        VolatilityChartResponse: {
            /** Ticker */
            ticker: string;
            /** Config Key */
            config_key: string;
            /** View Mode */
            view_mode: string;
            /** Unit */
            unit: string;
            /** As Of Date */
            as_of_date: string | null;
            /** Series */
            series: components["schemas"]["VolatilitySeries"][];
            /** State Ranges */
            state_ranges: components["schemas"]["VolatilityStateRange"][];
            /** Transitions */
            transitions: components["schemas"]["VolatilityTransition"][];
            /** Reference Lines */
            reference_lines: number[];
        };
        /**
         * VolatilityContextResponse
         * @description Latest point-in-time percentile context for one ticker/estimator (Phase 1).
         *
         *     ``historical_percentile`` is the internal 0.0–1.0 value; ``percentile_ordinal``
         *     is the 0–100 display form ("24th"). ``as_of_date`` is the snapshot date ``t``;
         *     ``information_through_date`` is ``t-1`` (the surface is lagged one day, §4.2).
         */
        VolatilityContextResponse: {
            /** Ticker */
            ticker: string;
            /** Config Key */
            config_key: string;
            /** Reference Estimator */
            reference_estimator: string;
            /** Historical Window */
            historical_window: string;
            /** As Of Date */
            as_of_date: string | null;
            /** Information Through Date */
            information_through_date: string | null;
            /** Current Volatility */
            current_volatility: number | null;
            /** Historical Percentile */
            historical_percentile: number | null;
            /** Percentile Ordinal */
            percentile_ordinal: number | null;
            /** Volatility Level */
            volatility_level: string;
            /** Insufficient History */
            insufficient_history: boolean;
            /** Direction */
            direction: string;
            /** Change 5D */
            change_5d: number | null;
            /** Change 20D */
            change_20d: number | null;
            /** Term Ratio */
            term_ratio: number | null;
            /** Term State */
            term_state: string;
            /** Instantaneous State */
            instantaneous_state: string;
            /** Confirmed State */
            confirmed_state: string;
            /** State Explanation */
            state_explanation: string;
            /** State Config Version */
            state_config_version: string;
            /** Estimator Agreement */
            estimator_agreement: string;
            /** Absolute Spread */
            absolute_spread: number | null;
            /** Relative Dispersion */
            relative_dispersion: number | null;
            /** Agreement Config Version */
            agreement_config_version: string;
            /** Price Volatility Context */
            price_volatility_context: string;
            /** Asset Return 20D */
            asset_return_20d: number | null;
            /** Vol Change 20D */
            vol_change_20d: number | null;
        };
        /**
         * VolatilityFeaturesResponse
         * @description Vol estimate lines for one ticker (Tab 5 chart). Series names are display
         *     labels; ``meta.method`` carries the raw key. ``available_methods`` lists the
         *     method keys that are non-empty for this ticker.
         */
        VolatilityFeaturesResponse: {
            /** Ticker */
            ticker: string;
            /** Series */
            series: components["schemas"]["NamedSeries"][];
            /** Available Methods */
            available_methods: string[];
        };
        /**
         * VolatilityLatestResponse
         * @description Latest-values table across all tickers.
         */
        VolatilityLatestResponse: {
            /** Methods */
            methods: string[];
            /** Rows */
            rows: components["schemas"]["VolLatestRow"][];
        };
        /**
         * VolatilityPercentileSeriesResponse
         * @description The historical-percentile line for one ticker/estimator/window (Phase 1).
         *
         *     ``series`` carries 0.0–1.0 percentile points (``unit="percentile"``);
         *     ``reference_lines`` are the band edges [0.20, 0.60, 0.80, 0.95] for the chart.
         */
        VolatilityPercentileSeriesResponse: {
            /** Ticker */
            ticker: string;
            /** Config Key */
            config_key: string;
            /** Reference Estimator */
            reference_estimator: string;
            /** Historical Window */
            historical_window: string;
            /**
             * Unit
             * @default percentile
             */
            unit: string;
            /** Series */
            series: components["schemas"]["NamedSeries"][];
            /** Reference Lines */
            reference_lines: number[];
        };
        /**
         * VolatilityPoint
         * @description A single (date, value) chart point; ``value`` is ``null`` for NaN/Inf.
         */
        VolatilityPoint: {
            /** Date */
            date: string;
            /** Value */
            value: number | null;
        };
        /**
         * VolatilityRatioChangeResponse
         * @description A Phase 2 derived-feature line: the 20D/60D term ratio or volatility change.
         *
         *     ``view`` selects the feature: ``"ratio"`` (rolling_20/rolling_60, ``unit`` =
         *     ``"ratio"``, reference lines [0.85, 1.00, 1.15]) or ``"change"`` (relative
         *     changes, ``unit`` = ``"relative_change"``, reference lines [-0.10, 0, 0.10]).
         */
        VolatilityRatioChangeResponse: {
            /** Ticker */
            ticker: string;
            /** Config Key */
            config_key: string;
            /** Reference Estimator */
            reference_estimator: string;
            /** View */
            view: string;
            /** Unit */
            unit: string;
            /** Series */
            series: components["schemas"]["NamedSeries"][];
            /** Reference Lines */
            reference_lines: number[];
        };
        /**
         * VolatilitySeries
         * @description A named chart trace with an explicit axis unit (Phase 6 typed chart data).
         */
        VolatilitySeries: {
            /** Name */
            name: string;
            /** Method */
            method: string | null;
            /** Unit */
            unit: string;
            /** Points */
            points: components["schemas"]["VolatilityPoint"][];
        };
        /**
         * VolatilityStateRange
         * @description A contiguous confirmed-state band for chart shading.
         */
        VolatilityStateRange: {
            /** Start */
            start: string;
            /** End */
            end: string;
            /** State */
            state: string;
        };
        /**
         * VolatilityStateRow
         * @description One asset's confirmed diagnostic state + supporting features (Phase 3 table).
         */
        VolatilityStateRow: {
            /** Ticker */
            ticker: string;
            /** Confirmed State */
            confirmed_state: string;
            /** Percentile Ordinal */
            percentile_ordinal: number | null;
            /** Current Volatility */
            current_volatility: number | null;
            /** Change 20D */
            change_20d: number | null;
            /** Term Ratio */
            term_ratio: number | null;
            /** Term State */
            term_state: string;
            /** Price Volatility Context */
            price_volatility_context: string;
            /** Asset Return 20D */
            asset_return_20d: number | null;
        };
        /**
         * VolatilityStateTableResponse
         * @description Latest confirmed-state across all assets (supplements the raw latest table).
         */
        VolatilityStateTableResponse: {
            /** As Of Date */
            as_of_date: string | null;
            /** Config Key */
            config_key: string;
            /** Reference Estimator */
            reference_estimator: string;
            /** State Config Version */
            state_config_version: string;
            /** Rows */
            rows: components["schemas"]["VolatilityStateRow"][];
        };
        /**
         * VolatilityTransition
         * @description A confirmed, cooldown-gated regime transition for a chart marker.
         */
        VolatilityTransition: {
            /** Date */
            date: string;
            /** Kind */
            kind: string;
            /** From State */
            from_state: string | null;
            /** To State */
            to_state: string | null;
            /** Label */
            label: string;
        };
        /**
         * YieldCurveResponse
         * @description 10Y/2Y yields, the 10Y-2Y spread, and curve-regime interpretation (Phase 2).
         *
         *     ``spread`` carries ``meta={'fill':'tozeroy'}``. ``curve_regime`` is the
         *     bull/bear steepening/flattening classification over time (categorical);
         *     ``inverted_intervals`` are the ``[{start, end}]`` spans where the spread is
         *     inverted (for shading); ``current_regime`` is the latest classified label.
         */
        YieldCurveResponse: {
            gs10: components["schemas"]["NamedSeries"];
            gs2: components["schemas"]["NamedSeries"];
            spread: components["schemas"]["NamedSeries"];
            curve_regime: components["schemas"]["CategoricalSeries"];
            /** Inverted Intervals */
            inverted_intervals: {
                [key: string]: unknown;
            }[];
            /** Current Regime */
            current_regime: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_scenarios_api_v1_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenariosResponse"];
                };
            };
        };
    };
    nav_comparison_api_v1_backtest_results_nav_comparison_get: {
        parameters: {
            query?: {
                /** @description Comma-separated scenario ids (case-sensitive). Omit for all. */
                scenario_ids?: string | null;
                /** @description Comma-separated benchmark tickers (TLT,AGG,SHY). Omit for all three. */
                benchmarks?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavComparisonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    returns_api_v1_backtest_results_returns_get: {
        parameters: {
            query?: {
                /** @description Comma-separated scenario ids (case-sensitive). Omit for all. */
                scenario_ids?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReturnsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    returns_diagnostic_api_v1_backtest_results_returns_diagnostic_get: {
        parameters: {
            query?: {
                /** @description Comma-separated scenario ids (case-sensitive). Omit for all. */
                scenario_ids?: string | null;
                /** @description ISO start date (clipped to data range). */
                start?: string | null;
                /** @description ISO end date (clipped to data range). */
                end?: string | null;
                /** @description Return-filter for the scatter: all | abs_gt_1pct | abs_gt_2pct | worst_1pct | best_1pct | extremes_20. */
                filter_mode?: string;
                /** @description Rows per diagnostic table. */
                table_limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReturnsDiagnosticResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    returns_diagnostic_point_api_v1_backtest_results_returns_diagnostic_point_get: {
        parameters: {
            query: {
                /** @description Scenario id of the clicked point. */
                scenario_id: string;
                /** @description ISO date of the clicked point. */
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReturnsPointDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_api_v1_backtest_results__scenario_id__daily_get: {
        parameters: {
            query?: {
                /** @description Comma-separated column subset. Default: scalar display set. */
                columns?: string | null;
                /** @description Max rows to return (pagination). */
                limit?: number | null;
                /** @description Row offset (pagination). */
                offset?: number;
            };
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestDailyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tearsheet_api_v1_tearsheet__scenario_id__get: {
        parameters: {
            query?: {
                /** @description Annual risk-free rate (decimal). */
                risk_free_rate?: number;
                /** @description Trading periods per year. */
                periods_per_year?: number;
            };
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TearsheetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    etf_prices_api_v1_etf_prices_get: {
        parameters: {
            query?: {
                /** @description Comma-separated tickers (e.g. TLT,AGG,SHY). Omit for all. */
                tickers?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtfPricesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    etf_price_stats_api_v1_etf_prices_stats_get: {
        parameters: {
            query?: {
                /** @description Comma-separated tickers (e.g. TLT,AGG,SHY). Omit for all. */
                tickers?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtfPriceStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    volatility_features_api_v1_volatility_features_get: {
        parameters: {
            query: {
                /** @description Ticker, e.g. TLT (required). */
                ticker: string;
                /** @description Comma-separated method keys. Default: all available. */
                methods?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolatilityFeaturesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    volatility_latest_api_v1_volatility_features_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolatilityLatestResponse"];
                };
            };
        };
    };
    volatility_audit_api_v1_volatility_features_audit_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolatilityAuditResponse"];
                };
            };
        };
    };
    volatility_chart_api_v1_volatility_features_chart_get: {
        parameters: {
            query: {
                /** @description Ticker, e.g. TLT (required). */
                ticker: string;
                /** @description Reference estimator key. */
                estimator?: string;
                /** @description Historical window: 3Y | 5Y | 10Y | Full. */
                window?: string;
                /** @description View: volatility | percentile | ratio | change | dispersion. */
                view?: string;
                /** @description Min observations before a percentile is emitted. */
                min_periods?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolatilityChartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    volatility_context_api_v1_volatility_features_context_get: {
        parameters: {
            query: {
                /** @description Ticker, e.g. TLT (required). */
                ticker: string;
                /** @description Reference estimator key. */
                estimator?: string;
                /** @description Historical window: 3Y | 5Y | 10Y | Full. */
                window?: string;
                /** @description Min observations before a percentile is emitted. */
                min_periods?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolatilityContextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    volatility_percentile_api_v1_volatility_features_percentile_get: {
        parameters: {
            query: {
                /** @description Ticker, e.g. TLT (required). */
                ticker: string;
                /** @description Reference estimator key. */
                estimator?: string;
                /** @description Historical window: 3Y | 5Y | 10Y | Full. */
                window?: string;
                /** @description Min observations before a percentile is emitted. */
                min_periods?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolatilityPercentileSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    volatility_state_table_api_v1_volatility_features_state_table_get: {
        parameters: {
            query?: {
                /** @description Reference estimator key. */
                estimator?: string;
                /** @description Historical window: 3Y | 5Y | 10Y | Full. */
                window?: string;
                /** @description Min observations before a percentile is emitted. */
                min_periods?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolatilityStateTableResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    volatility_agreement_api_v1_volatility_features_agreement_get: {
        parameters: {
            query: {
                /** @description Ticker, e.g. TLT (required). */
                ticker: string;
                /** @description Historical window for the panel percentiles. */
                window?: string;
                /** @description Min observations before a percentile is emitted. */
                min_periods?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimatorAgreementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    volatility_derived_api_v1_volatility_features_derived_get: {
        parameters: {
            query: {
                /** @description Ticker, e.g. TLT (required). */
                ticker: string;
                /** @description Reference estimator key (drives the change view). */
                estimator?: string;
                /** @description Derived view: ratio | change | dispersion. */
                view?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolatilityRatioChangeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    macro_api_v1_macro_get: {
        parameters: {
            query?: {
                /** @description Comma-separated indicator keys (raw or derived, e.g. cpi_yoy, real_policy_rate). Default: all. */
                indicators?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MacroResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    yield_curve_api_v1_macro_yield_curve_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YieldCurveResponse"];
                };
            };
        };
    };
    snapshot_api_v1_macro_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MacroSnapshotResponse"];
                };
            };
        };
    };
    regime_timeline_api_v1_macro_regime_timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegimeTimelineResponse"];
                };
            };
        };
    };
    conditional_returns_api_v1_macro_conditional_returns_get: {
        parameters: {
            query?: {
                /** @description Restrict to one ETF (TLT/AGG/SHY). Default: all. */
                etf?: string | null;
                /** @description Below this observation count a regime row is flagged 'thin'. */
                min_observations?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConditionalReturnsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forward_return_scatter_api_v1_macro_forward_return_scatter_get: {
        parameters: {
            query?: {
                /** @description ETF whose forward return is the Y axis (TLT/AGG/SHY). */
                etf?: string;
                /** @description Macro indicator key for the X axis. */
                indicator?: string;
                /** @description Forward horizon: 1m / 3m / 6m / 12m. */
                horizon?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForwardReturnScatterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    strategies_api_v1_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategiesResponse"];
                };
            };
        };
    };
    trigger_backtest_api_v1_jobs_backtest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"][];
                };
            };
        };
    };
    job_status_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
