/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * DB-exists health gate
         * @description Report whether the configured SQLite DB is present.
         *
         *     Always HTTP 200 so the client can read the body and decide; ``status`` is
         *     ``"ok"`` only when the DB file exists, otherwise ``"degraded"``.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List persisted scenario ids
         * @description Distinct persisted scenario ids (sorted) and their count.
         */
        get: operations["list_scenarios_api_v1_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest-results/nav-comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * NAV comparison + summary
         * @description Per-scenario NAV lines, dashed B&H benchmarks, and the summary table (Tab 1).
         */
        get: operations["nav_comparison_api_v1_backtest_results_nav_comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest-results/returns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily returns scatter
         * @description Columnar daily-return series per scenario for the WebGL scatter (Tab 2).
         */
        get: operations["returns_api_v1_backtest_results_returns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest-results/returns-diagnostic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns Analysis diagnostic payload
         * @description Enriched per-scenario scatter + boxplot distribution + worst/best/dispersion
         *     tables for the redesigned Returns Analysis view. Ships every scenario at once
         *     so the page toggles curve visibility client-side (no refetch).
         *
         *     Returns an ``ORJSONResponse`` directly: the service builds the (large) payload
         *     as a plain dict and we skip Pydantic response validation for speed
         *     (``response_model`` above still drives the OpenAPI schema).
         */
        get: operations["returns_diagnostic_api_v1_backtest_results_returns_diagnostic_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest-results/returns-diagnostic/point": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Single-point diagnostic detail (click drilldown)
         * @description Rich per-point context for the Returns Analysis click drilldown (one row).
         */
        get: operations["returns_diagnostic_point_api_v1_backtest_results_returns_diagnostic_point_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest-results/{scenario_id}/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily rows for a scenario
         * @description Raw daily rows for one scenario (Tab 3 table).
         */
        get: operations["daily_api_v1_backtest_results__scenario_id__daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tearsheet/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full tearsheet for a scenario
         * @description Metrics + equity/drawdown/rolling curves + exposure/regime/benchmark tables.
         */
        get: operations["tearsheet_api_v1_tearsheet__scenario_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/etf-prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ETF close-price lines
         * @description One close-price :class:`NamedSeries` per ticker (Tab 4 chart).
         */
        get: operations["etf_prices_api_v1_etf_prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/etf-prices/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ETF price statistics
         * @description Per-ticker first/last/min/max close + total return (Tab 4 table).
         */
        get: operations["etf_price_stats_api_v1_etf_prices_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/volatility-features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vol estimate lines for a ticker
         * @description Per-method annualized-vol lines for one ticker (Tab 5 chart).
         */
        get: operations["volatility_features_api_v1_volatility_features_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/volatility-features/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest vol per ticker
         * @description Latest annualized vol per method per ticker (Tab 5 table).
         */
        get: operations["volatility_latest_api_v1_volatility_features_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Macro indicator series
         * @description One series per requested macro indicator (each on its own date axis).
         */
        get: operations["macro_api_v1_macro_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro/yield-curve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 10Y/2Y yields + spread
         * @description 10Y and 2Y yields plus the 10Y-2Y spread.
         */
        get: operations["yield_curve_api_v1_macro_yield_curve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Strategy registry introspection
         * @description Flatten the ``STRATEGIES`` registry so the UI can decode scenario names.
         */
        get: operations["strategies_api_v1_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger a backtest run
         * @description Launch a backtest over the registry (or a subset); returns 202 + the job.
         */
        post: operations["trigger_backtest_api_v1_jobs_backtest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List backtest jobs
         * @description All jobs this process has seen (in-process registry).
         */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll a backtest job
         * @description Status of one job; 404 if the id is unknown to this process.
         */
        get: operations["job_status_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a running backtest
         * @description Terminate a queued/running job's subprocess; a no-op if it already finished.
         */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BacktestDailyResponse
         * @description Endpoint 4 (Tab 3 raw table): one scenario's daily rows, paginated.
         *
         *     ``table`` carries the requested columns (default: the scalar display set the
         *     Streamlit tab shows). ``total_rows`` is the unpaginated count for the scenario.
         */
        BacktestDailyResponse: {
            /** Scenario Id */
            scenario_id: string;
            /** Total Rows */
            total_rows: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number | null;
            table: components["schemas"]["TableModel"];
        };
        /**
         * BacktestJobRequest
         * @description Trigger body: an optional subset of strategy names (``None`` = whole registry).
         */
        BacktestJobRequest: {
            /** Strategy Names */
            strategy_names?: string[] | null;
        };
        /**
         * EtfPriceStatsResponse
         * @description The price-statistics table as a list of typed rows.
         */
        EtfPriceStatsResponse: {
            /** Stats */
            stats: components["schemas"]["PriceStat"][];
        };
        /**
         * EtfPricesResponse
         * @description Close-price lines, one :class:`NamedSeries` per ticker (Tab 4 chart).
         */
        EtfPricesResponse: {
            /** Series */
            series: components["schemas"]["NamedSeries"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description DB-exists gate -- replaces the Streamlit ``app.py`` ``DB_PATH.exists()`` check.
         *
         *     ``status`` is ``"ok"`` only when the configured SQLite DB file is present and
         *     readable. The React ``HealthGate`` blocks the app on anything else.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Db Exists */
            db_exists: boolean;
            /** Db Path */
            db_path: string;
            /** Api Version */
            api_version: string;
        };
        /**
         * JobStatus
         * @description A backtest job's state (polled via ``GET /jobs/{job_id}``).
         */
        JobStatus: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Strategy Names */
            strategy_names: string[] | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Scenario Ids Written */
            scenario_ids_written: string[] | null;
            /** Detail */
            detail: string | null;
            /** Progress Current */
            progress_current: number | null;
            /** Progress Total */
            progress_total: number | null;
            /** Progress Strategy */
            progress_strategy: string | null;
        };
        /**
         * MacroResponse
         * @description One :class:`NamedSeries` per requested indicator (name = indicator key).
         */
        MacroResponse: {
            /** Series */
            series: components["schemas"]["NamedSeries"][];
        };
        /**
         * NamedSeries
         * @description A named chart trace: a legend label plus its (x, y) points.
         */
        NamedSeries: {
            /** Name */
            name: string;
            /** Points */
            points: components["schemas"]["SeriesPoint"][];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * NavComparisonResponse
         * @description Tab 1: scenario NAV lines + dashed B&H benchmark lines + summary table.
         */
        NavComparisonResponse: {
            /** Start Date */
            start_date: string | null;
            /** Initial Nav */
            initial_nav: number;
            /** Scenario Series */
            scenario_series: components["schemas"]["NamedSeries"][];
            /** Benchmark Series */
            benchmark_series: components["schemas"]["NamedSeries"][];
            /** Summary */
            summary: components["schemas"]["ScenarioSummaryRow"][];
        };
        /**
         * PriceStat
         * @description Per-ticker price statistics (Tab 4 table). Floats are nullable per §6.
         *
         *     ``total_return`` is a decimal fraction (``last/first - 1``), e.g. ``0.42`` =
         *     42% -- formatting is the client's job (§4.1).
         */
        PriceStat: {
            /** Ticker */
            ticker: string;
            /** First Close */
            first_close: number | null;
            /** Last Close */
            last_close: number | null;
            /** Min Close */
            min_close: number | null;
            /** Max Close */
            max_close: number | null;
            /** Total Return */
            total_return: number | null;
        };
        /**
         * ReturnsDiagnosticResponse
         * @description The full Returns Analysis diagnostic payload (scatter + boxplot + tables).
         *
         *     The entire scenario universe is shipped at once (``series`` / ``distribution``
         *     cover every scenario), so the page toggles curve visibility client-side via
         *     the Plotly legend with no further fetches. ``default_visible`` names the few
         *     scenarios drawn visible on first load; the rest start ``legendonly``.
         */
        ReturnsDiagnosticResponse: {
            /** Available Scenarios */
            available_scenarios: components["schemas"]["ScenarioMeta"][];
            /** Default Visible */
            default_visible: string[];
            /** Date Min */
            date_min: string | null;
            /** Date Max */
            date_max: string | null;
            /** Filter Mode */
            filter_mode: string;
            /** Series */
            series: components["schemas"]["ReturnsDiagnosticSeries"][];
            /** Distribution */
            distribution: components["schemas"]["ReturnsDistributionSeries"][];
            worst: components["schemas"]["TableModel"];
            best: components["schemas"]["TableModel"];
            dispersion: components["schemas"]["TableModel"];
        };
        /**
         * ReturnsDiagnosticSeries
         * @description One scenario's scatter points (date-range + return-filter scoped).
         *
         *     Columnar (parallel arrays) to avoid per-point object allocation, mirroring
         *     ``ReturnsScatterSeries``. Intentionally lean -- date + return only -- so the
         *     full grid ships cheaply and legend toggles never refetch. Rich per-point
         *     context lives in the diagnostic tables and the on-demand click drilldown
         *     (``ReturnsPointDetail``), not in this array.
         */
        ReturnsDiagnosticSeries: {
            /** Scenario Id */
            scenario_id: string;
            /** Scenario Label */
            scenario_label: string;
            /** Dates */
            dates: string[];
            /** Returns */
            returns: (number | null)[];
        };
        /**
         * ReturnsDistributionSeries
         * @description One scenario's full date-range return distribution (for the boxplot).
         *
         *     Not restricted by the chart's return-filter mode -- a boxplot of only the
         *     outliers would be meaningless, so this always spans the selected date range.
         */
        ReturnsDistributionSeries: {
            /** Scenario Id */
            scenario_id: string;
            /** Scenario Label */
            scenario_label: string;
            /** Returns */
            returns: (number | null)[];
        };
        /**
         * ReturnsPointDetail
         * @description Rich diagnostic detail for a single (scenario, date) -- the click drilldown.
         *
         *     Fetched on demand (one row) so the main scatter payload stays lean. ``lines``
         *     are the pre-formatted, missing-field-omitted diagnostic lines the panel renders.
         */
        ReturnsPointDetail: {
            /** Scenario Id */
            scenario_id: string;
            /** Scenario Label */
            scenario_label: string;
            /** Date */
            date: string | null;
            /** Daily Return */
            daily_return: number | null;
            /** Lines */
            lines: string[];
        };
        /**
         * ReturnsResponse
         * @description Tab 2: one columnar return series per scenario (rendered via Plotly WebGL).
         */
        ReturnsResponse: {
            /** Series */
            series: components["schemas"]["ReturnsScatterSeries"][];
        };
        /**
         * ReturnsScatterSeries
         * @description Daily returns for one scenario, columnar (parallel ``dates``/``returns``).
         */
        ReturnsScatterSeries: {
            /** Scenario Id */
            scenario_id: string;
            /** Dates */
            dates: string[];
            /** Returns */
            returns: (number | null)[];
        };
        /**
         * ScenarioMeta
         * @description A scenario's readable label + parsed metadata, for the UI filters/picker.
         *
         *     Shipped for *every* available scenario (not just the selected ones) so the
         *     family / volatility-method / target-vol filters and the multi-select can be
         *     populated without a second round-trip. Metadata fields are nullable: an
         *     unparseable id degrades gracefully rather than failing.
         */
        ScenarioMeta: {
            /** Scenario Id */
            scenario_id: string;
            /** Scenario Label */
            scenario_label: string;
            /** Family */
            family: string | null;
            /** Lookback */
            lookback: number | null;
            /** Vol Method */
            vol_method: string | null;
            /** Cov Lookback */
            cov_lookback: number | null;
            /** Ewma Lambda */
            ewma_lambda: number | null;
            /** Target Vol */
            target_vol: number | null;
        };
        /**
         * ScenarioSummaryRow
         * @description One row of the "Scenario Performance Summary" table (Tab 1).
         */
        ScenarioSummaryRow: {
            /** Scenario Id */
            scenario_id: string;
            /** Final Nav */
            final_nav: number | null;
            /** Total Return */
            total_return: number | null;
            /** Max Drawdown */
            max_drawdown: number | null;
            /** Annualized Volatility */
            annualized_volatility: number | null;
        };
        /**
         * ScenariosResponse
         * @description Distinct persisted scenario ids (sorted) plus their count.
         */
        ScenariosResponse: {
            /** Scenarios */
            scenarios: string[];
            /** Count */
            count: number;
        };
        /**
         * SeriesPoint
         * @description A single (x, y) point. ``value`` is ``None`` for NaN/Inf (§6).
         */
        SeriesPoint: {
            /** Date */
            date: string;
            /** Value */
            value: number | null;
        };
        /**
         * StrategiesResponse
         * @description The whole registry plus the currently-selected live strategy name.
         */
        StrategiesResponse: {
            /** Live Strategy */
            live_strategy: string;
            /** Strategies */
            strategies: components["schemas"]["StrategySummary"][];
        };
        /**
         * StrategySummary
         * @description A flattened view of one ``StrategyConfig`` (selected knobs from its sub-configs).
         */
        StrategySummary: {
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Starting Weight Source */
            starting_weight_source: string;
            /** Use Vol Scaling */
            use_vol_scaling: boolean;
            /** Vol Scaling Power */
            vol_scaling_power: number;
            /** Use Covariance Scaling */
            use_covariance_scaling: boolean;
            /** Target Portfolio Vol */
            target_portfolio_vol: number;
            /** Cov Method */
            cov_method: string;
            /** Is Live */
            is_live: boolean;
        };
        /**
         * TableModel
         * @description A generic table: column order plus list-of-records rows (values JSON scalars or null).
         */
        TableModel: {
            /** Columns */
            columns: string[];
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
        };
        /**
         * TearsheetMetricsModel
         * @description Flat view of ``TearsheetMetrics`` (all 26 fields).
         */
        TearsheetMetricsModel: {
            /** Scenario Id */
            scenario_id: string;
            /** Start Date */
            start_date: string;
            /** End Date */
            end_date: string;
            /** Total Return */
            total_return: number | null;
            /** Cagr */
            cagr: number | null;
            /** Annualized Volatility */
            annualized_volatility: number | null;
            /** Sharpe */
            sharpe: number | null;
            /** Sortino */
            sortino: number | null;
            /** Max Drawdown */
            max_drawdown: number | null;
            /** Calmar */
            calmar: number | null;
            /** Var 95 */
            var_95: number | null;
            /** Cvar 95 */
            cvar_95: number | null;
            /** Worst Day */
            worst_day: number | null;
            /** Best Day */
            best_day: number | null;
            /** Skew */
            skew: number | null;
            /** Excess Kurtosis */
            excess_kurtosis: number | null;
            /** Avg Turnover */
            avg_turnover: number | null;
            /** Annualized Turnover */
            annualized_turnover: number | null;
            /** Total Cost */
            total_cost: number | null;
            /** Cost Drag */
            cost_drag: number | null;
            /** Daily Hit Rate */
            daily_hit_rate: number | null;
            /** Avg Win */
            avg_win: number | null;
            /** Avg Loss */
            avg_loss: number | null;
            /** Payoff Ratio */
            payoff_ratio: number | null;
            /** Profit Factor */
            profit_factor: number | null;
            /** Parametric Var 95 */
            parametric_var_95: number | null;
        };
        /**
         * TearsheetResponse
         * @description Full tearsheet: metrics + equity/drawdown/rolling curves + summary tables.
         */
        TearsheetResponse: {
            summary: components["schemas"]["TearsheetMetricsModel"];
            equity_curve: components["schemas"]["NamedSeries"];
            drawdown_curve: components["schemas"]["NamedSeries"];
            /** Rolling Metrics */
            rolling_metrics: components["schemas"]["NamedSeries"][];
            exposure_summary: components["schemas"]["TableModel"] | null;
            regime_summary: components["schemas"]["TableModel"] | null;
            benchmark_summary: components["schemas"]["TableModel"] | null;
            /** Regime Match Rate */
            regime_match_rate: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VolLatestRow
         * @description Latest annualized vol per method for one ticker (Tab 5 table).
         */
        VolLatestRow: {
            /** Ticker */
            ticker: string;
            /** Date */
            date: string | null;
            /** Rolling 20 */
            rolling_20: number | null;
            /** Rolling 60 */
            rolling_60: number | null;
            /** Ewma 94 */
            ewma_94: number | null;
            /** Ewma 97 */
            ewma_97: number | null;
            /** Garch */
            garch: number | null;
        };
        /**
         * VolatilityFeaturesResponse
         * @description Vol estimate lines for one ticker (Tab 5 chart). Series names are display
         *     labels; ``meta.method`` carries the raw key. ``available_methods`` lists the
         *     method keys that are non-empty for this ticker.
         */
        VolatilityFeaturesResponse: {
            /** Ticker */
            ticker: string;
            /** Series */
            series: components["schemas"]["NamedSeries"][];
            /** Available Methods */
            available_methods: string[];
        };
        /**
         * VolatilityLatestResponse
         * @description Latest-values table across all tickers.
         */
        VolatilityLatestResponse: {
            /** Methods */
            methods: string[];
            /** Rows */
            rows: components["schemas"]["VolLatestRow"][];
        };
        /**
         * YieldCurveResponse
         * @description 10Y/2Y yields and the 10Y-2Y spread (spread carries meta={'fill':'tozeroy'}).
         */
        YieldCurveResponse: {
            gs10: components["schemas"]["NamedSeries"];
            gs2: components["schemas"]["NamedSeries"];
            spread: components["schemas"]["NamedSeries"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_scenarios_api_v1_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenariosResponse"];
                };
            };
        };
    };
    nav_comparison_api_v1_backtest_results_nav_comparison_get: {
        parameters: {
            query?: {
                /** @description Comma-separated scenario ids (case-sensitive). Omit for all. */
                scenario_ids?: string | null;
                /** @description Comma-separated benchmark tickers (TLT,AGG,SHY). Omit for all three. */
                benchmarks?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavComparisonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    returns_api_v1_backtest_results_returns_get: {
        parameters: {
            query?: {
                /** @description Comma-separated scenario ids (case-sensitive). Omit for all. */
                scenario_ids?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReturnsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    returns_diagnostic_api_v1_backtest_results_returns_diagnostic_get: {
        parameters: {
            query?: {
                /** @description Comma-separated scenario ids (case-sensitive). Omit for all. */
                scenario_ids?: string | null;
                /** @description ISO start date (clipped to data range). */
                start?: string | null;
                /** @description ISO end date (clipped to data range). */
                end?: string | null;
                /** @description Return-filter for the scatter: all | abs_gt_1pct | abs_gt_2pct | worst_1pct | best_1pct | extremes_20. */
                filter_mode?: string;
                /** @description Rows per diagnostic table. */
                table_limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReturnsDiagnosticResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    returns_diagnostic_point_api_v1_backtest_results_returns_diagnostic_point_get: {
        parameters: {
            query: {
                /** @description Scenario id of the clicked point. */
                scenario_id: string;
                /** @description ISO date of the clicked point. */
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReturnsPointDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_api_v1_backtest_results__scenario_id__daily_get: {
        parameters: {
            query?: {
                /** @description Comma-separated column subset. Default: scalar display set. */
                columns?: string | null;
                /** @description Max rows to return (pagination). */
                limit?: number | null;
                /** @description Row offset (pagination). */
                offset?: number;
            };
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestDailyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tearsheet_api_v1_tearsheet__scenario_id__get: {
        parameters: {
            query?: {
                /** @description Annual risk-free rate (decimal). */
                risk_free_rate?: number;
                /** @description Trading periods per year. */
                periods_per_year?: number;
            };
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TearsheetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    etf_prices_api_v1_etf_prices_get: {
        parameters: {
            query?: {
                /** @description Comma-separated tickers (e.g. TLT,AGG,SHY). Omit for all. */
                tickers?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtfPricesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    etf_price_stats_api_v1_etf_prices_stats_get: {
        parameters: {
            query?: {
                /** @description Comma-separated tickers (e.g. TLT,AGG,SHY). Omit for all. */
                tickers?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtfPriceStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    volatility_features_api_v1_volatility_features_get: {
        parameters: {
            query: {
                /** @description Ticker, e.g. TLT (required). */
                ticker: string;
                /** @description Comma-separated method keys. Default: all available. */
                methods?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolatilityFeaturesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    volatility_latest_api_v1_volatility_features_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolatilityLatestResponse"];
                };
            };
        };
    };
    macro_api_v1_macro_get: {
        parameters: {
            query?: {
                /** @description Comma-separated indicator keys. Default: all. */
                indicators?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MacroResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    yield_curve_api_v1_macro_yield_curve_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YieldCurveResponse"];
                };
            };
        };
    };
    strategies_api_v1_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategiesResponse"];
                };
            };
        };
    };
    trigger_backtest_api_v1_jobs_backtest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"][];
                };
            };
        };
    };
    job_status_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
